version: '3'

services:
  react:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: yarn dev
    stdin_open: true
    tty: true
    ports:
      - 5173:5173
    volumes:
      - .:/react

  cypress:
    image: "cypress/included:12.3.0"
    depends_on:
      - react
    working_dir: /cypress
    volumes:
      - ./cypress:/cypress
