name: Cypress Pull Request

on: pull_request

jobs:
  pr-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Start the React app and wait for it to be available
        run: |
          docker-compose up -d react
          until nc -z localhost 5173; do sleep 1; done
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests

      # Start the Cypress container and run the tests
      - name: Start Cypress container
        run: docker-compose run --rm cypress yarn run cypress run #--config baseUrl=http://react:5173

      # Stop the application container after the tests have finished
      - name: Stop application container
        run: docker-compose down
      # - name: Cypress run
      #   uses: cypress-io/github-action@v5
        # with:
        #   build: yarn build
        #   start: yarn dev